import { Host, Booking, Review } from '../types';

export const MOCK_HOSTS: Host[] = [
  {
    id: '1',
    user_id: 'u1',
    display_name: 'Truth Coffee',
    bio: 'Award-winning steampunk café in the heart of Cape Town CBD. We have a secure storage room and friendly staff to look after your bags while you explore the city.',
    avatar_url: undefined,
    location_name: 'Cape Town CBD',
    latitude: -33.9249,
    longitude: 18.4241,
    business_type: 'cafe',
    photos: [],
    price_per_bag_per_day: 80,
    max_bags: 10,
    available_from: '07:00',
    available_until: '17:00',
    available_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    rating: 4.9,
    review_count: 143,
    response_rate: 98,
    is_active: true,
    created_at: '2025-01-01',
  },
  {
    id: '2',
    user_id: 'u2',
    display_name: "Priya's Home",
    bio: 'Local resident in Sea Point with a secure entrance hallway and lockable storage cupboard. Happy to help fellow travellers!',
    avatar_url: undefined,
    location_name: 'Sea Point',
    latitude: -33.9073,
    longitude: 18.3914,
    business_type: 'home',
    photos: [],
    price_per_bag_per_day: 50,
    max_bags: 4,
    available_from: '08:00',
    available_until: '21:00',
    available_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    rating: 4.8,
    review_count: 67,
    response_rate: 100,
    is_active: true,
    created_at: '2025-02-01',
  },
  {
    id: '3',
    user_id: 'u3',
    display_name: 'The Bookshop on Kloof',
    bio: 'Independent bookshop on Kloof Street. Drop your bags and browse the neighbourhood — we\'ll keep everything safe.',
    avatar_url: undefined,
    location_name: 'Gardens, Kloof Street',
    latitude: -33.9282,
    longitude: 18.4137,
    business_type: 'shop',
    photos: [],
    price_per_bag_per_day: 60,
    max_bags: 6,
    available_from: '09:00',
    available_until: '18:00',
    available_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    rating: 4.7,
    review_count: 34,
    response_rate: 95,
    is_active: true,
    created_at: '2025-03-01',
  },
  {
    id: '4',
    user_id: 'u4',
    display_name: 'Camps Bay Surf Shack',
    bio: 'Surf shop right on Camps Bay beachfront. Drop your luggage and hit the beach or the promenade.',
    avatar_url: undefined,
    location_name: 'Camps Bay',
    latitude: -33.9503,
    longitude: 18.3762,
    business_type: 'shop',
    photos: [],
    price_per_bag_per_day: 90,
    max_bags: 8,
    available_from: '08:00',
    available_until: '19:00',
    available_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    rating: 4.6,
    review_count: 89,
    response_rate: 92,
    is_active: true,
    created_at: '2025-01-15',
  },
  {
    id: '5',
    user_id: 'u5',
    display_name: "Marco's Guesthouse",
    bio: 'Boutique guesthouse in Green Point. We welcome day-trippers to leave luggage even if not staying with us.',
    avatar_url: undefined,
    location_name: 'Green Point',
    latitude: -33.9058,
    longitude: 18.4088,
    business_type: 'guesthouse',
    photos: [],
    price_per_bag_per_day: 70,
    max_bags: 12,
    available_from: '07:00',
    available_until: '22:00',
    available_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    rating: 4.9,
    review_count: 211,
    response_rate: 99,
    is_active: true,
    created_at: '2024-11-01',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    booking_id: 'b1',
    reviewer_id: 'u10',
    host_id: '1',
    reviewer_name: 'Sarah T.',
    rating: 5,
    comment: 'Absolutely brilliant! Staff were so friendly and my bags were perfectly safe. Would 100% use again.',
    created_at: '2025-12-01',
  },
  {
    id: 'r2',
    booking_id: 'b2',
    reviewer_id: 'u11',
    host_id: '1',
    reviewer_name: 'James M.',
    rating: 5,
    comment: 'Perfect location in the CBD. Easy drop-off, easy pickup. The café is amazing too!',
    created_at: '2025-11-20',
  },
  {
    id: 'r3',
    booking_id: 'b3',
    reviewer_id: 'u12',
    host_id: '2',
    reviewer_name: 'Anika R.',
    rating: 5,
    comment: 'Priya was so welcoming. Felt completely safe leaving my suitcase. This is genius.',
    created_at: '2025-12-05',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b10',
    traveller_id: 'me',
    host_id: '1',
    host: MOCK_HOSTS[0],
    drop_off_date: '2026-06-20',
    drop_off_time: '09:00',
    pick_up_date: '2026-06-20',
    pick_up_time: '15:00',
    bag_count: 2,
    total_price: 160,
    status: 'confirmed',
    pin_code: '7492',
    created_at: '2026-06-15',
  },
];
