import { Host, Booking, Review } from '../types';

export const MOCK_HOSTS: Host[] = [/*
  {
    id: 'host-1',
    user_id: 'user-1',
    display_name: 'Sea Point Café & Co',
    bio: 'Friendly café in the heart of Sea Point.',
    business_type: 'cafe',
    location_name: 'Sea Point',
    latitude: -33.9175,
    longitude: 18.3823,
    price_per_bag_per_day: 35,
    rating: 4.8,
    review_count: 42,
    response_rate: 98,
    available_from: '07:00',
    available_until: '20:00',
    available_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    max_bags: 10,
    photos: [],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'host-2',
    user_id: 'user-2',
    display_name: 'V&A Waterfront Hotel',
    bio: 'Luxury hotel storage in the iconic V&A Waterfront precinct.',
    business_type: 'hotel',
    location_name: 'V&A Waterfront',
    latitude: -33.9042,
    longitude: 18.4197,
    price_per_bag_per_day: 60,
    rating: 4.9,
    review_count: 87,
    response_rate: 100,
    available_from: '06:00',
    available_until: '22:00',
    available_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    max_bags: 30,
    photos: [],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'host-3',
    user_id: 'user-3',
    display_name: 'Gardens Guesthouse',
    bio: 'Charming guesthouse near the Company\'s Garden.',
    business_type: 'guesthouse',
    location_name: 'Gardens',
    latitude: -33.9258,
    longitude: 18.4132,
    price_per_bag_per_day: 30,
    rating: 4.7,
    review_count: 29,
    response_rate: 95,
    available_from: '08:00',
    available_until: '21:00',
    available_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    max_bags: 8,
    photos: [],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'host-4',
    user_id: 'user-4',
    display_name: 'Green Point Hostel',
    bio: 'Backpacker-friendly hostel near the Cape Town Stadium.',
    business_type: 'hostel',
    location_name: 'Green Point',
    latitude: -33.9089,
    longitude: 18.3989,
    price_per_bag_per_day: 20,
    rating: 4.5,
    review_count: 63,
    response_rate: 92,
    available_from: '07:00',
    available_until: '23:00',
    available_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    max_bags: 20,
    photos: [],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'host-5',
    user_id: 'user-5',
    display_name: 'De Waterkant Airbnb',
    bio: 'Stylish De Waterkant apartment — store your bags while you explore.',
    business_type: 'airbnb',
    location_name: 'De Waterkant',
    latitude: -33.9167,
    longitude: 18.4133,
    price_per_bag_per_day: 25,
    rating: 4.6,
    review_count: 18,
    response_rate: 90,
    available_from: '09:00',
    available_until: '20:00',
    available_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    max_bags: 6,
    photos: [],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'host-6',
    user_id: 'user-6',
    display_name: 'Camps Bay Tours',
    bio: 'Tour operator on the Camps Bay strip. Store and explore the beach.',
    business_type: 'tour_operator',
    location_name: 'Camps Bay',
    latitude: -33.9508,
    longitude: 18.3773,
    price_per_bag_per_day: 40,
    rating: 4.9,
    review_count: 54,
    response_rate: 99,
    available_from: '08:00',
    available_until: '18:00',
    available_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    max_bags: 15,
    photos: [],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'host-7',
    user_id: 'user-7',
    display_name: 'Clifton Guesthouse',
    bio: 'Exclusive guesthouse steps from Clifton\'s famous beaches.',
    business_type: 'guesthouse',
    location_name: 'Clifton',
    latitude: -33.9433,
    longitude: 18.3739,
    price_per_bag_per_day: 45,
    rating: 4.8,
    review_count: 31,
    response_rate: 96,
    available_from: '08:00',
    available_until: '20:00',
    available_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    max_bags: 10,
    photos: [],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'host-8',
    user_id: 'user-8',
    display_name: 'Bo-Kaap Coffee House',
    bio: 'Vibrant café in the colourful Bo-Kaap neighbourhood.',
    business_type: 'cafe',
    location_name: 'Bo-Kaap',
    latitude: -33.9196,
    longitude: 18.4103,
    price_per_bag_per_day: 28,
    rating: 4.7,
    review_count: 47,
    response_rate: 94,
    available_from: '07:30',
    available_until: '19:00',
    available_days: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],
    max_bags: 12,
    photos: [],
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
  },
*/];

export interface Runner {
  id: string;
  name: string;
  vehicle: string;
  location_name: string;
  rating: number;
  review_count: number;
  price_per_bag: number;
  delivery_radius_km: number;
  eta_minutes: number;
  is_active: boolean;
}

export const MOCK_RUNNERS: Runner[] = [];

export const MOCK_REVIEWS: Review[] = [];
export const MOCK_BOOKINGS: Booking[] = [];
