import { Host, Booking, Review } from '../types';

export const MOCK_HOSTS: Host[] = [
  {
    id: 'host-1',
    display_name: 'Sea Point Café & Co',
    business_type: 'cafe',
    location_name: 'Sea Point',
    address: '120 Main Road, Sea Point, Cape Town',
    latitude: -33.9175,
    longitude: 18.3823,
    price_per_bag_per_day: 35,
    rating: 4.8,
    review_count: 42,
    response_rate: 98,
    available_from: '07:00',
    available_until: '20:00',
    max_bags: 10,
    description: 'Friendly café in the heart of Sea Point. Drop your bags and enjoy the promenade!',
    photos: [],
    verified: true,
    instant_book: true,
  },
  {
    id: 'host-2',
    display_name: 'V&A Waterfront Hotel',
    business_type: 'hotel',
    location_name: 'V&A Waterfront',
    address: 'Dock Road, V&A Waterfront, Cape Town',
    latitude: -33.9042,
    longitude: 18.4197,
    price_per_bag_per_day: 60,
    rating: 4.9,
    review_count: 87,
    response_rate: 100,
    available_from: '06:00',
    available_until: '22:00',
    max_bags: 30,
    description: 'Luxury hotel storage in the iconic V&A Waterfront precinct.',
    photos: [],
    verified: true,
    instant_book: true,
  },
  {
    id: 'host-3',
    display_name: 'Gardens Guesthouse',
    business_type: 'guesthouse',
    location_name: 'Gardens',
    address: '45 Bloem Street, Gardens, Cape Town',
    latitude: -33.9258,
    longitude: 18.4132,
    price_per_bag_per_day: 30,
    rating: 4.7,
    review_count: 29,
    response_rate: 95,
    available_from: '08:00',
    available_until: '21:00',
    max_bags: 8,
    description: 'Charming guesthouse near the Company\'s Garden. Secure bag storage available.',
    photos: [],
    verified: true,
    instant_book: true,
  },
  {
    id: 'host-4',
    display_name: 'Green Point Hostel',
    business_type: 'hostel',
    location_name: 'Green Point',
    address: '18 Somerset Road, Green Point, Cape Town',
    latitude: -33.9089,
    longitude: 18.3989,
    price_per_bag_per_day: 20,
    rating: 4.5,
    review_count: 63,
    response_rate: 92,
    available_from: '07:00',
    available_until: '23:00',
    max_bags: 20,
    description: 'Backpacker-friendly hostel near the Cape Town Stadium.',
    photos: [],
    verified: true,
    instant_book: true,
  },
  {
    id: 'host-5',
    display_name: 'De Waterkant Airbnb',
    business_type: 'airbnb',
    location_name: 'De Waterkant',
    address: '7 Loader Street, De Waterkant, Cape Town',
    latitude: -33.9167,
    longitude: 18.4133,
    price_per_bag_per_day: 25,
    rating: 4.6,
    review_count: 18,
    response_rate: 90,
    available_from: '09:00',
    available_until: '20:00',
    max_bags: 6,
    description: 'Stylish De Waterkant apartment — store your bags while you explore the neighbourhood.',
    photos: [],
    verified: true,
    instant_book: false,
  },
  {
    id: 'host-6',
    display_name: 'Camps Bay Tours',
    business_type: 'tour_operator',
    location_name: 'Camps Bay',
    address: 'Victoria Road, Camps Bay, Cape Town',
    latitude: -33.9508,
    longitude: 18.3773,
    price_per_bag_per_day: 40,
    rating: 4.9,
    review_count: 54,
    response_rate: 99,
    available_from: '08:00',
    available_until: '18:00',
    max_bags: 15,
    description: 'Tour operator on the Camps Bay strip. Store and explore the beach.',
    photos: [],
    verified: true,
    instant_book: true,
  },
  {
    id: 'host-7',
    display_name: 'Clifton Guesthouse',
    business_type: 'guesthouse',
    location_name: 'Clifton',
    address: '2nd Beach Road, Clifton, Cape Town',
    latitude: -33.9433,
    longitude: 18.3739,
    price_per_bag_per_day: 45,
    rating: 4.8,
    review_count: 31,
    response_rate: 96,
    available_from: '08:00',
    available_until: '20:00',
    max_bags: 10,
    description: 'Exclusive guesthouse steps from Clifton\'s famous beaches.',
    photos: [],
    verified: true,
    instant_book: true,
  },
  {
    id: 'host-8',
    display_name: 'Bo-Kaap Coffee House',
    business_type: 'cafe',
    location_name: 'Bo-Kaap',
    address: '71 Wale Street, Bo-Kaap, Cape Town',
    latitude: -33.9196,
    longitude: 18.4103,
    price_per_bag_per_day: 28,
    rating: 4.7,
    review_count: 47,
    response_rate: 94,
    available_from: '07:30',
    available_until: '19:00',
    max_bags: 12,
    description: 'Vibrant café in the colourful Bo-Kaap neighbourhood. Great coffee, safe storage.',
    photos: [],
    verified: true,
    instant_book: true,
  },
];

export const MOCK_REVIEWS: Review[] = [];
export const MOCK_BOOKINGS: Booking[] = [];
